CREATE TABLE IF NOT EXISTS accounts
(
    accountId  INT PRIMARY KEY AUTO_INCREMENT,
    name       VARCHAR(100)   NOT NULL,
    document   VARCHAR(100)   NOT NULL,
    balance    NUMERIC(10, 2) NOT NULL DEFAULT 0,
    status     VARCHAR(100)   NOT NULL,
    type       VARCHAR(100)   NOT NULL,
    created_at TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP               DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

