services:
    discovery-service:
        build: ./discovery-service
        container_name: discovery-service
        ports:
            - "8761:8761"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
            interval: 30s
            timeout: 10s
            retries: 5
        depends_on:
            - kafka
        networks:
            - my-network
    gateway-service:
        build: ./gateway-service
        container_name: gateway-service
        ports:
            - "8080:8080"
        depends_on:
            - kafka
            - discovery-service
        networks:
            - my-network
    account-service:
        build: ./account-service
        container_name: account-service
        ports:
            - "8081:8081"
        depends_on:
            - kafka
            - discovery-service
        networks:
            - my-network
    notification-service:
        build: ./notification-service
        container_name: notification-service
        ports:
            - "8082:8082"
        depends_on:
            - kafka
            - discovery-service
        networks:
            - my-network
    transaction-service:
        build: ./transaction-service
        container_name: transaction-service
        ports:
            - "8083:8083"
        depends_on:
            - kafka
            - discovery-service
        networks:
            - my-network
    kafka:
        image: confluentinc/cp-kafka:latest
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
        depends_on:
            - zookeeper
        networks:
            - my-network
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - my-network
    kafdrop:
        image: obsidiandynamics/kafdrop
        ports:
            - "9000:9000"
        environment:
            KAFKA_BROKERCONNECT: kafka:29092
            JVM_OPTS: "-Xms32M -Xmx64M"
        depends_on:
            - kafka
        networks:
            - my-network
networks:
    my-network:
        driver: bridge